# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = name
ENV POSTGRES_USER = name
ENV POSTGRES_PASSWORD = pass

# Expose the PostgreSQL port
EXPOSE 5432