export const updateHeroSchema = {
  type: 'object',
  properties: {
    file: {
      type: 'string',
      format: 'binary',
    },
    name: { type: 'string' },
    world_id: { type: 'number' },
    user_id: { type: 'string' },
    cha: { type: 'number' },
    con: { type: 'number' },
    dex: { type: 'number' },
    int: { type: 'number' },
    str: { type: 'number' },
    wis: { type: 'number' },
    notes: { type: 'string' },
    armorBonus: { type: 'number' },
    buff_hp: { type: 'number' },
    copper_coins: { type: 'number' },
    silver_coins: { type: 'number' },
    electrum_coins: { type: 'number' },
    gold_coins: { type: 'number' },
    platinum_coins: { type: 'number' },
    current_hp: { type: 'number' },
    max_hp: { type: 'number' },
    temp_hp: { type: 'number' },
    subrace_id: { type: 'number' },
    race_id: { type: 'number' },
    creation_done: { type: 'boolean' },
    traits: { type: 'string' },
    ideal: { type: 'string' },
    bounds: { type: 'string' },
    flaws: { type: 'string' },
    armor_id: { type: 'number' },
    shield_id: { type: 'number' },
    armor_bonus: { type: 'number' },
    iexperiencent: { type: 'number' },
    warlock_pact_id: { type: 'number' },
    armor_types_prof: {
      type: 'array',
      items: { type: 'string' },
    },
    weapon_types_prof: {
      type: 'array',
      items: { type: 'string' },
    },
    languages_ids: {
      type: 'array',
      items: { type: 'number' },
    },
    tools_ids: {
      type: 'array',
      items: { type: 'number' },
    },
  },
};
